Port 22
ListenAddress 0.0.0.0

PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
AllowUsers agent

AllowTcpForwarding yes
GatewayPorts no
X11Forwarding no
PermitTunnel no

AuthorizedKeysFile .ssh/authorized_keys
PermitUserEnvironment HTTP_PROXY,HTTPS_PROXY,NO_PROXY
UsePAM yes
